name: mordevpy27
dependencies:
  - python=2.7
  - scipy
  - numpy
  - pandas
  - xarray
  - pymongo
  - jupyter
  - ipykernel
  - nb_conda_kernels
  - dask
  - distributed
  - ipyparallel
  - ephem
  - astropy
  - dill
  - cython
  - lxml
  - Sphinx
  - basemap
  - dnspython
  - pip:
    - pint
    - PyHamcrest
    - spacetrack
    - orbit-predictor
    - easygui
    - strict-rfc3339
    - openexr